animal-squad/project-s-FE

src/App.tsx
src/Pages/JoinPage.tsx
src/Pages/LoginPage.tsx
src/Pages/MainPage.tsx

- 파일 구조를 개선했습니다.
- Pages 폴더를 만들었습니다.
- Buttons 폴더를 만들었습니다.
- Layout 폴더를 만들었습니다. (Header, Sidebar 등 추가)
- Layout Component를 생성했습니다.
- src/layout 아래에 Header.tsx를 생성했습니다.
- src/layout 아래에 Sidebar.tsx를 생성했습니다.
- Main page를 생성했습니다.
- src/pages 아래에 MainPage.tsx를 생성했습니다.
- 컴포넌트 이름을 변경 및 위치 재조정을 진행했습니다.
- src/pages 아래로 Login.tsx를 이동시켰습니다.
- Login.tsx의 이름을 LoginPage.tsx로 변경했습니다.
- src/pages 아래로 JoinPage.tsx를 이동시켰습니다.
- Login.tsx의 이름을 JoinPage.tsx로 변경했습니다.
- App.tsx에 "import React"를 추가했습니다.
- App.tsx에 해당 코드를 추가했습니다.
```typescript
import React from "react";
```
#1

#1 Feat: Layout Component 및 Main Page 생성

---

package-lock.json
package.json
src/Layout/Sidebar.tsx
src/Pages/MainPage.tsx

- Sidebar 디자인을 추가했습니다.
- Sidebar 전체 부분을 추가했습니다.
- Storage, Links, Texts 버튼을 추가했습니다.
- 임시로 Log Out 버튼의 위치를 잡았습니다. (추후 변경 가능)
- Sidebar 애니메이션을 추가했습니다.
- 열릴 때, 닫힐 때 애니메이션이 추가됩니다.
- 글씨에도 애니메이션이 추가됩니다.
- 아이콘 위치를 기준으로 애니메이션이 작동하여 아이콘은 움직이지 않습니다.
<닫혔을 때>
<열렸을 때>
#3 #4
만약 PR이 병합될 때 함께 닫고자 하는 이슈는 아래와 같이 작성해주세요
resolves #4

#4 Style: Sidebar 디자인 및 애니메이션 적용

---

package-lock.json
package.json
src/Layout/Header.tsx
src/Layout/LinkHeader.tsx
src/Pages/MainPage.tsx
src/store/tabStore.ts

- Header 디자인을 추가했습니다.
- Header 자리에 올 Tab을 제작했습니다.
- 간단한 애니메이션을 추가했습니다.
- 각 Tab끼리 클릭시 하단의 바가 움직이는 형식의 애니메이션을 추가했습니다.
- Main Page에 적용했습니다.
- 기존의 "Main Page" 글씨를 없애고, 임시로 "Storage", "Links", "Texts" 탭을 만들었습니다.
- 하단의 텍스트도 함께 변경됩니다.
- 페이지가 리로딩되지는 않습니다.
<Storage 선택 시>
<Links 선택 시>
<Texts 선택 시>
#3
resolves #3

#3 Feat: Header 구현

---

.env
src/Layout/Sidebar.tsx
src/Pages/LoginPage.tsx

로그인 및 로그아웃을 위한 Axios 통신 코드를 제작했습니다.
- 로그인의 경우 LoginPage에서 진행합니다. axios GET 요청을 사용합니다.
- 로그아웃의 경우 Sidebar에서 진행합니다. axios GET 요청을 사용합니다.
<로그인 함수>
```typescript
const handleLogin = async () => {
try {
const response = await axios.get(`${import.meta.env.VITE_BACKEND_DOMAIN}/auth/google`);
console.log("Login successful:", response.data);
// 로그인 성공 시 메인 페이지로 이동
} catch (error) {
console.error("Login failed:", error);
// 로그인 실패 시 필요한 처리
}
};
```
<로그아웃 함수>
```typescript
const handleLogoutClick = async () => {
if (handleLogout) {
try {
const response = await axios.get(`${import.meta.env.VITE_BACKEND_DOMAIN}/auth/logout`);
console.log("Logout successful:", response.data);
} catch (error) {
console.error("Logout failed:", error);
// 로그아웃 실패 시 처리
}
} else { …
```

#14 Feat: 로그인 및 로그아웃 통신 구현

---

vite.config.ts

vite.config.js에 proxy 세팅을 추가했습니다.
CORS 에러를 회피할 수 있습니다.
#18

Fix: CORS 세팅 추가

---

.env
src/Pages/LoginPage.tsx

하드코딩된 이미지 및 애니메이션 파일에 대해서 .env 파일에 변수를 지정하고 불러오는 방식으로 리팩토링 진행했습니다.
```typescript
const lottieAnimation = import.meta.env.VITE_LOTTIE_FILE;
const googleLoginButton = import.meta.env.VITE_GOOGLE_BUTTON;
```
```typescript
VITE_GOOGLE_BUTTON = "src/assets/images/web_neutral_rd_ctn.svg"
VITE_LOTTIE_FILE = "src/assets/animations/fileAnimation.lottie"
```
resolves #22

#22 Refactor: 이미지 및 애니메이션 경로 수정

---

.env
src/Layout/Sidebar.tsx
src/Pages/LoginPage.tsx

- Backend Domain을 수정합니다.
- LoginPage에서 요청 주소를 수정합니다.
- Sidebar에서 요청 주소를 수정합니다.
LogIn
```typescript
const handleLogin = async () => {
try {
window.location.href = `${
import.meta.env.VITE_BACKEND_DOMAIN
}/api/auth/google`;
// 로그인 성공 시 메인 페이지로 이동
} catch (error) {
console.error("Login failed:", error);
// 로그인 실패 시 필요한 처리
}
};
```
LogOut
```typescript
const handleLogoutClick = async () => {
if (handleLogout) {
try {
window.location.href = `${
import.meta.env.VITE_BACKEND_DOMAIN
}/api/auth/logout`;
} catch (error) {
console.error("Logout failed:", error);
// 로그아웃 실패 시 처리
}
} else {
setSelected(title);
}
};
```
resolves #30

Feat: [Hotfix] .env 및 LoginPage, Sidebar 요청 주소 수정

---

nginx.conf

Nginx 내 404 에러를 custom handler로 보내기 위한 구문 누락에 따른 코드 수정
resolves #34

#34 Fix: Nginx Error Interceptor 누락

---

nginx.conf

Nginx 내 404 에러 발생시 index.html으로 호스팅 하는 코드가 동작하지 않음
resolves #36

#36 Fix: 404 페이지 intercept 비정상 작동

---

Jenkinsfile

#39
- Jenkinsfile 추가함(Jenkins에서 pipeline build 할 때 사용되는 파일)

CI/CD: Jenkinsfile 추가

---

package-lock.json
package.json
src/components/FileComponent_ListView.tsx
src/components/FileList_ListView.tsx
vite.config.ts

- Table 제목 및 공유 (+ 복사) 버튼
- Table 내부 목록 DTO 통일
- Hyperlink 지원
목록 클릭으로 열린 새 창들
- Background에서 열리진 않습니다.
resolves #42

#42 Feat: 바구니 내부 화면 구현

---

public/assets/icons/Bucket_Icon_Black.svg
src/App.tsx
src/Pages/UnauthorizedPage.tsx
src/Pages/UnsharedPage.tsx

- 로그인되어있지 않은 사용자가 서비스의 임의의 링크에 접속했을 때 redirect 할 페이지를 구현했습니다.
- 로그인 화면으로 이동시키는 버튼이 포함됩니다.
- 공유하지 않은 바구니의 링크로 사용자가 접속했을 때 redirect할 페이지를 구현했습니다.
- 이전 페이지로 이동시키는 버튼이 포함됩니다.
Unshared (사용자가 공유 안함) 페이지
Unauthorized (로그인 인식 불가) 페이지
resolves #45

Feat: 에러 페이지 제작

---

src/components/FolderComponent.tsx
src/components/FolderComponent_GridView.tsx
src/components/FolderList.tsx
src/store/FileIndexStore.ts

- 바구니 페이지의 View 형태를 바꿨습니다.
- Grid View에서 List View로 변경되었습니다.
- 각 row에는 바구니 이름, 바구니의 링크 수, 생성일자, 공유 여부가 표시됩니다.
- DTO를 일치시켰습니다.
- 통신 코드를 포함합니다. 지금 보이는 데이터는 기본 데이터입니다.
resolves #44

#44 Feat: 바구니 페이지 List View로 변경

---

src/App.tsx
src/components/FileList_ListView.tsx
src/components/FolderComponent.tsx

- Modal 창을 구현했습니다.
- 창 내부에 switch 버튼을 추가했습니다.
- Public / Private 선택 가능합니다.
- 창 내부에 URL 표시창 및 복사버튼을 추가했습니다.
- 각종 업데이트 로직을 추가했습니다.
resolves #48

#48 Feat: 공유 버튼을 누를 시 뜨는 modal 추가

---

src/components/FileList_ListView.tsx

- 링크 조회 시 조회 API를 호출합니다.
```typescript
<a
onClick={() => {
// PUT 요청으로 조회수 증가
axios
.put(
`${import.meta.env.VITE_BACKEND_DOMAIN}/api/link/${
record.linkId
}/view`
)
.then(() => {
console.log("View count updated for link:", record.linkId);
})
.catch((error) => {
console.error("Failed to update view count:", error);
});
window.open(record.URL); // URL 열기
}}
>
{text}
</a>
```
resolves #50

Feat: 조회 시 통신 기능 구현

---

src/components/FileList_ListView.tsx

- 다른 사용자의 공유된 바구니를 복사하는 기능을 추가합니다.
- 공유되지 않은 바구니에 접근 시 에러페이지로 이동합니다.
resolves #52

#52 Feat: 바구니 복사 기능 구현

---

index.html
public/assets/images/Icon_16.svg
src/Layout/Sidebar.tsx
src/Pages/LoginPage.tsx
src/components/FileList_ListView.tsx
src/store/FileIndexStore.ts
src/store/userStore.ts

- withCredentials : true 코드를 전부 추가합니다.
- 탭 아이콘을 지정합니다.
- 탭 title을 지정합니다.
- 유저 정보를 받아오는 API 통신 코드를 작성합니다.
resolves #55

Feat: 구글 로그인 정보 받아오기 추가

---

src/components/FolderList.tsx
src/store/FileIndexStore.ts

- API 통신 주소를 정상적으로 변경합니다.
```typescript
const response = await axios.get(`${import.meta.env.VITE_BACKEND_DOMAIN}/api/bucket`, {
params: { page, take: 10 }, // 페이지와 데이터 수를 파라미터로 전달
withCredentials: true,
});
```
resolves #58

#58 HotFix: 바구니 호출 API 주소 변경

---

src/components/FileList_ListView.tsx
src/components/FolderComponent.tsx
src/store/FileIndexStore.ts

- 바구니의 페이지네이션을 수정합니다
- 링크의 페이지네이션을 수정합니다.
```typescript
```
resolves #60

#60 Fix: 페이지네이션 수정

---

src/Layout/Sidebar.tsx

- Sidebar에 notifs를 반영
```typescript
notifs={meta?.totalBuckets}
```
resolves #62

Fix: Sidebar Notifs 추가

---

Jenkinsfile

#68
- Jenkinsfile 수정
#68 
resolves #68

#68 CI/CD: Jenkinsfile 수정

---

src/components/FileList_ListView.tsx

- 바구니 페이지에 삭제 버튼이 추가됩니다
- 삭제 버튼 클릭시 모달이 나오도록 변경됩니다.
- 복사 모달과는 별개로 등장합니다
- 모달에서 Delete 클릭 시 Delete 요청이 송신됩니다
- isMine이 false일 경우 버튼이 뜨지 않게 설정합니다
resolves #73

#73 Feat: 바구니 삭제 기능 구현

---

src/components/FileList_ListView.tsx

- 바구니 제목을 수정할 수 있는 아이콘을 추가합니다.
- 아이콘 클릭 시 모달이 뜨도록 합니다.
resolves #75

#75 Feat: 바구니 제목 수정 기능 추가

---

src/Layout/Sidebar.tsx
src/components/FileList_ListView.tsx

- 버킷 삭제 시 리다이렉트 되는 경로를 변경합니다
- 로그아웃 시 API 호출 대신 새 창을 열게 됩니다.
resolves #79

#79 Fix: 버킷 삭제 시 리다이렉트 경로 변경 및 로그아웃 시 로직 변경

---

src/components/FileList_ListView.tsx

- 각 row에 연필 모양 아이콘을 추가했습니다.
- 클릭 시 모달이 열립니다.
- 수정 완료 후 OK 시 통신을 진행합니다.
resolves #77

#77 Feat: 링크 제목 수정 기능 추가

---

src/components/FileList_ListView.tsx
src/components/FolderComponent.tsx
src/components/FolderList.tsx
src/store/FileIndexStore.ts

- 모든 axios 요청 시 401 에러가 발생한 경우 /unauthorized로 리다이렉션합니다
- 기존 401 코드 (/unshared)는 403으로 변경되었습니다
resolves #82

Feat: axios 요청 시 401 에러 관련 리다이렉션 추가

---

src/Pages/LandingPage.tsx

- Landing Page의 글씨 색상을 더 명확하게 지정합니다.
- 로그인 버튼의 위치를 수정합니다.
resolves #84

#84 Fix: 랜딩 페이지 가운데 글씨 색상 및 로그인 버튼 위치 조정

---

src/components/FileList_ListView.tsx

- API 요청 주소를 변경합니다.
resolves #87

#87 HotFix: api 요청 주소 수정

---

src/components/FileList_ListView.tsx

- unautorized -> unauthorized 오타 수정
```typescript
navigate("/unautorized"); // 오타
navigate("/unauthorized"); // 수정 완료
```
resolves #89

#89 HotFix: unauthorized 페이지 오타 수정

---

src/components/FileList_ListView.tsx
src/components/FolderComponent.tsx

- 바구니 전체 뷰에 바구니 제목 수정 기능 추가
- 바구니 내부 뷰에서 바구니 제목 수정 기능 삭제
resolves #91

#91 Feat: 바구니 내부 table 배치 변경 및 title 수정 바구니뷰로 이전

---

src/Pages/LandingPage.tsx

- 랜딩페이지에서 로그인 여부 체크
- 로그인 확인 시 메인페이지로 이동
로그인 확인 요청
```typescript
axios
.get(`${import.meta.env.VITE_BACKEND_DOMAIN}api/user/check`, {
withCredentials: true,
})
.then((response) => {
if (response.status === 200) navigate("/main/bucket");
});
```
resolves #93

#93 Feat: 랜딩 페이지에서 로그인 여부 체크 및 이동

---

src/Pages/LandingPage.tsx

- Axios 통신 요청 코드의 오타를 수정
```typescript
.get(`${import.meta.env.VITE_BACKEND_DOMAIN}api/user/check`, { // x
.get(`${import.meta.env.VITE_BACKEND_DOMAIN}/api/user/check`, { // o
// 틀린그림찾기
```
resolves #95

Fix: 랜딩 페이지에서 사용자 정보 요청하는 API 오타 수정

---

package-lock.json
package.json
src/components/FileList_ListView.tsx

- 태그 수정 기능을 구현했습니다.
- 사용자가 태그를 수정할 수 있습니다.
- 태그 수정 시 API 요청이 보내집니다.
- 요청 수를 제한하기 위해서 debouncing을 2000ms로 적용합니다.
- 태그 수가 0일 경우 '기타'가 붙습니다.
- '기타'는 삭제 불가능합니다.
- '기타'를 포함한 상태에서 다른 태그가 붙으면 '기타' 태그가 제거됩니다.
resolves #76

#76 Feat: 태그 수정 / 삭제 기능 추가

---

src/Layout/Sidebar.tsx

#100
- Sidebar 로그아웃 버튼 위에 홈버튼 구현
- 버튼 기능 구현
resolves #100

#100 Feat: Sidebar에 홈버튼 추가

---

src/Pages/LandingPage.tsx
src/components/FileList_ListView.tsx
src/ui/sticky-scroll-reveal.tsx

- 이미지 오류 정상화
- 태그 오류 정상화
resolves #106

#106 HotFix: 태그 빈자리 'Borderless' 삭제 및 태그 null로 들어올 시 '기타'태그 부여

---

Dockerfile

#108
- Dockerfile node base image 16-> 22로 변경
#108 
resovles #108

#108 Refactor: Dockerfile node base image 변경

---

src/Pages/LandingPage.tsx

- 버튼의 디자인을 두종류로 설정합니다.
resolves #113

#113 Feat: 로그인 버튼 기존 디자인 + 구글 로그인 버튼 표시 기능 추가

---

src/Layout/Sidebar.tsx

- sidebar에 notif = 0인 경우에 버그가 생기는 부분을 해결했습니다.
resolves #116

#116 HotFix: sidebar notif 버그 수정

---

src/App.tsx
src/Layout/NewHeader.tsx
src/components/Bucket_GridView.tsx
src/index.css
src/ui/Searchbox.tsx
tailwind.config.js

- UI 개선
- 반응형 일정부분 적용
resolves #118

#118 Feat: UI 개선 : 바구니 페이지

---

src/App.tsx
src/components/NewComponent/Bucket_InsideVIew.tsx
src/components/NewComponent/Bucket_View.tsx
src/ui/FloatButton.tsx
src/ui/TagSelect.tsx

- 바구니 내부 페이지를 제작합니다
- Title 및 Title 메뉴를 구현합니다
- 컨텐츠 및 컨텐츠 메뉴를 구현합니다
- 체크박스 및 전체 선택을 구현합니다
- 체크박스의 상태에 따라 삭제 메뉴가 움직이도록 구현합니다
resolves #120

#120 Feat: UI 개선 : 바구니 내부 페이지 #120

---

Jenkinsfile

#121
- Jenkinsfile 수정
#121 
resolves #121

fix: Jenkinsfile 누락된 내용 추가

---

src/Layout/NewHeader.tsx
src/Layout/Sidebar.tsx
src/components/FileList_GridView.tsx
src/components/FolderComponent.tsx
src/components/FolderList.tsx
src/components/NewComponent/Bucket_InsideVIew.tsx
src/store/BucketStore.ts
src/store/linkStore.ts

- 바구니 상세조회 추가
- 프로필 적용 추가
- 바구니 제목 수정 모달 및 통신 코드 추가
- 바구니 공유 모달 추가
- 바구니 공유 통신 로직 변경 (debouncing)
- 복사 버튼 클릭시 복사 완료 표시 표기 (message)
- 바구니 삭제 모달 추가
- 바구니 삭제 통신 기능 추가
- 바구니 복사 모달 추가
- 바구니 복사 통신 추가
resolve #124

#124 Feat: 업데이트된 UI에 기능 추가 : 바구니

---

.env
src/App.tsx

- App.tsx 변경
- .env 변경
resolves #129

#129 Feat: App.tsx 렌더링 주소 변경 및 API 통신 주소 변경

---

tailwind.config.js

CommonJS -> ES로 변경합니다
resolves #138

#138 Fix: tailwindcss config file CommonJS -> ES 변경

---

src/App.tsx
src/components/NewComponent/Bucket_InsideView.tsx

- 바구니 뷰의 링크 관련 기능들을 추가합니다
- 링크 제목 수정을 추가합니다
- 링크 삭제 기능을 추가합니다
- 링크 n개 삭제 기능을 추가합니다
- 태그 수정 기능을 추가합니다
resolves #128

#128 Feat: 업데이트된 UI에 기능 추가 : 링크

---

src/App.tsx
src/Layout/NewHeader.tsx
src/Pages/Bucket_InsidePage.tsx
src/Pages/Bucket_ViewPage.tsx
src/Pages/Link_ViewPage.tsx
src/store/BucketStore.ts
src/store/searchLinkStore.ts
src/ui/Searchbox.tsx
src/ui/TagSelect_Search.tsx

#123 Feat: 링크 뷰 / 검색 페이지 추가

---

src/App.tsx
src/Pages/Bucket_ViewPage.tsx
src/Pages/Link_SearchPage.tsx
src/store/LinkSearchStore.ts
src/store/TagSearchStore.ts
src/ui/Searchbox.tsx

- 검색 페이지 및 기능 구현
- Pagination 기능 구현
resolves #142

#142 Feat: 검색 페이지 구현

---

src/ui/FloatButton.tsx

- FloatButton에 링크 추가 기능 구현
- Enter로도 submit 가능
```typescript
```
resolves #144

#144 Feat: 링크 추가 기능 구현

---

src/Pages/Bucket_InsidePage.tsx
src/Pages/Link_SearchPage.tsx
src/Pages/Link_ViewPage.tsx

- window.open 기능 추가
- 조회수 업데이트 기능 추가
resolves #146

#146 Feat: 링크 클릭시 URL open 및 조회수 업데이트 기능 추가

---

src/Layout/NewHeader.tsx

- 프로필 클릭시 메뉴 추가
- 로그아웃 추가
resolves #148

#148 Feat: 프로필 사진 클릭시 메뉴 추가 및 로그아웃 추가

---

src/Pages/Bucket_InsidePage.tsx
src/Pages/Link_SearchPage.tsx
src/Pages/Link_ViewPage.tsx

- Enter 키를 통한 통신 추가
```typescript
```
resolves #151

#151 Feat: 링크 / 바구니 제목 모달에서 Enter 키로 submit 가능하도록 수정

---

src/Layout/NewHeader.tsx
src/Pages/Bucket_InsidePage.tsx
src/Pages/Bucket_ViewPage.tsx
src/Pages/LandingPage.tsx
src/Pages/LoginPage.tsx

- Header 유저 정보 fetch
- 바구니 클릭시 내부 뷰로 navigate
resolves #154

#154 Fix: Header 유저 정보 fetch 코드 작성

---

Jenkinsfile_test_server

#150
- Test 서버 전용 Jenkinsfile 추가

feat: Test 서버 전용 Jenkinsfile 추가

---

Jenkinsfile_test_server

fix: Jenkinsfile 수정

---

src/store/LinkSearchStore.ts
src/ui/Searchbox.tsx

- loading 상태를 도입해서 요청을 제한합니다
resolves #161

Fix: 검색 요청이 5000개 가는 버그 수정

---

.env.test
Jenkinsfile_test_server

#166
- Test 서버 전용 .env 파일 추가 및 Test Jenkinsfile build cmd 수정

feat: Test 서버 전용 .env 파일 추가 및 Jenkinsfile 수정

---

package.json

#166
- package.json 수정
resolves #166

fix: package.json 수정

---

src/Pages/Link_SearchPage.tsx
src/ui/Searchbox.tsx

- search URL에 query 추가
- base64로 인코딩 후 navigate된 페이지에서 디코딩
- page는 searchbox에서는 null 상태로 이동 / 이동 후에 page가 null이라면 &page = 1로 이동.
```typescript
useEffect(() => {
if (!page) {
const encodedQuery = btoa(query);
const defaultPage = 1;
navigate(`/search?query=${encodedQuery}&page=${defaultPage}`, { replace: true });
}
}, [page, query, navigate]);
```
resolves #164

Feat: search URL에 query 추가

---

src/Pages/Bucket_ViewPage.tsx
src/ui/Searchbox.tsx
src/ui/TagSelect_Search.tsx

- Bucket에 hover 시 커서가 포인터로 바뀝니다.
- 검색어 입력 후 돋보기 아이콘 클릭시 검색이 됩니다.
- 돋보기 아이콘 hover 시 커서가 포인터로 바뀝니다.
- 태그 검색 모달의 tagselect가 outlined로 바뀝니다.
resolves #173

#173 Feat: 디테일 추가

---

src/Pages/Link_SearchPage.tsx
src/Pages/Link_ViewPage.tsx

API에서는 linkId의 값을 받는 것으로 설정되어 있는데 넘겨주는 데이터 형식이 data : {linkId} 이기 때문에 에러가 발생해서 해당 내용을 수정하였습니다.
링크 다수 삭제 시 모달이 닫히는 함수가 빠져있어 추가하였습니다.
```typescript
```
#175

Fix: change dto format to link delete API routing

---

src/store/TagSearchStore.ts

링크 조회 / 링크 태그 필터 조회 부분의 형식을 변경된 API에 맞춰 수정하였습니다.
- GET 요청에서 POST 요청으로 변경
- 태그를 param이 아닌 body로 전송하도록 변경
```typescript
```
resolves #177

#177 Fix: 링크 태그 조회 라우터 수정

---

src/Pages/Bucket_InsidePage.tsx

바구니 공유 기능 버그
- 공유 권한의 변화 상태가 제대로 전달되지 않은 부분 수정
- 공유 권한의 상태 저장에 따라 수정 이후에 모달을 열어도 해당 값이 반영되도록 수정
바구니 제목 수정 버그
- 바구니 제목 수정 후 새로고침을 해야만 변경 내역을 볼 수 있는 것을 수정
```typescript
```
resolves #179

#179 Fix: 바구니 내부 페이지 공유, 제목 수정 버그 수정

---

.env.test
Jenkinsfile
Jenkinsfile_test_server
package.json
src/Pages/Bucket_ViewPage.tsx
src/Pages/Link_SearchPage.tsx
src/ui/Searchbox.tsx
src/ui/TagSelect_Search.tsx

- 전역 기능 내부로 수정
```typescript
```
resolves #163

#163 Refactor: 검색 기능 리팩토링 #163

---

src/Pages/Link_SearchPage.tsx

- 요청 1번만 가도록 수정
- Pagination 수정
resolves #184

#184 Fix: 검색 시 요청 1번만 가도록 수정

---

src/Pages/Link_ViewPage.tsx
src/store/TagSearchStore.ts
src/ui/FloatButton.tsx

- 요청이 여러번 가는 문제를 수정합니다
- 더미데이터를 삭제합니다
resolves #188

#188 Fix: link API 요청 시 요청 많이 가는 버그 수정 + 더미데이터 삭제 #188

---

src/Pages/Link_SearchPage.tsx
src/store/TagSearchStore.ts

#190 Fix: 검색 버그 수정

---

src/Pages/LandingPage.tsx

- Landing Page에 chrome extension 설치 페이지 추가
resolves #196

#196 Feat: Landing Page에 Chrome extension 설치 페이지 추가

---

src/Pages/Bucket_InsidePage.tsx

- isPublic의 초기값을 false에서 isShared로 변경
resolves #198

#198 Fix: 공유 모달 내에서 isPublic 상태를 제대로 받아오지 못하는 버그 수정

---

src/Pages/Bucket_InsidePage.tsx
src/Pages/Bucket_ViewPage.tsx
src/Pages/Link_SearchPage.tsx
src/Pages/Link_ViewPage.tsx
src/store/linkStore.ts

- 모든 화면에 항목 개수에 따라 동적으로 높이 계산하도록 적용
resolves #201

#201 Fix: 항목 수에 따라 페이지 길이가 변동되도록 수정

---

src/Pages/Bucket_InsidePage.tsx
src/Pages/Link_SearchPage.tsx

- 수정 요청 양식 맞지 않는 부분 수정
resolves #204

#204 Fix: 링크 삭제 요청 수정

---

src/Pages/Bucket_InsidePage.tsx
src/Pages/Link_SearchPage.tsx

- 요청 이후에 모달 닫기 추가
resolves #204

Fix: 링크 삭제 요청 수정

---

src/Pages/UnsharedPage.tsx

이전 페이지로 naviagate 시 무한 루프 방지
```typescript
```
resolves #208

#208 Fix: Unauthorized 페이지 이전 페이지 -> 바구니 페이지 수정

---

src/Pages/UnauthorizedPage.tsx
src/Pages/UnsharedPage.tsx

- 에러 페이지의 가독성을 위하여 배경색 추가
resolves #210

#210 Fix: 에러 페이지 배경색 변경

---

src/Pages/Bucket_InsidePage.tsx

- 복사 수정 후 모달 닫기 기능 추가
resolves #213

#213 Fix: 복사 로직 수정 후 모달 닫기 추가

---

src/Pages/LandingPage.tsx

- Landing Page Header z-index 수정
resolves #216

#216 Fix: Landing Page Header z-index 수정

---

src/Pages/Bucket_InsidePage.tsx
src/Pages/Link_SearchPage.tsx
src/Pages/Link_ViewPage.tsx

- 모든 link view의 오류 수정
resolves #218

#218 Fix: 전체 선택 오류 수정

---

src/ui/FloatButton.tsx

정규표현식 사용하여 링크 유효성 검사
resolves #220

#220 Fix: 단일 링크 추가 수정

---

src/ui/FloatButton.tsx

- 단일 링크 추가 로직 변경
resolves #223

#223 Fix: 단일 링크 추가 로직 변경
